services:
  - type: web
    name: Uchiha-Bot
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: VERIFY_TOKEN
        value: uchiha-verify
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ID
        sync: false
      - key: WHODBOK_API_KEY
        sync: false
